### ISSUE TITLE
llvm is built and bottled in debug mode

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/homebrew-core#8405] opened 2018-07-12 16:55 UTC
I'm simply referring to PR 7571 here without re-elaborating the details. Here's the benchmark:

Running `time clang++ test.cpp -o test` with bottled/built version of current formula:
```
real	0m1.699s
user	0m1.671s
sys	0m0.020s

real	0m1.691s
user	0m1.661s
sys	0m0.023s

real	0m2.094s
user	0m1.942s
sys	0m0.106s
```

Same test on `-O3` flag:

```
real	0m0.018s
user	0m0.009s
sys	0m0.009s

real	0m0.012s
user	0m0.008s
sys	0m0.003s

real	0m0.018s
user	0m0.011s
sys	0m0.007s
```

I think I've made the point very strong by now. Let me know if you are still interested in fixing it.

**Comment by iMichka** [comment] 2018-07-18 19:57
Hi. Thanks for the report. It is definitely something we should have a second look at. I have some more urgent emergencies to fix at the moment, I hope I will have some time for this next week.

**Comment by iMichka** [comment] 2018-08-07 21:37
```
cmake -G Unix Makefiles /tmp/llvm-20180807-27034-1vnq6eh/llvm-6.0.1.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/llvm/6.0.1_2 -DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-Wno-dev
-DLLVM_OPTIMIZED_TABLEGEN=ON
-DLLVM_INCLUDE_DOCS=OFF
-DLLVM_INSTALL_UTILS=ON
-DWITH_POLLY=ON
-DLINK_POLLY_INTO_TOOLS=ON
-DLLVM_TARGETS_TO_BUILD=all
-DLIBOMP_ARCH=x86_64
-DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON
-DLLVM_ENABLE_RTTI=ON
-DLLVM_ENABLE_EH=ON
-DLLVM_BUILD_LLVM_DYLIB=ON
-DCLANG_DEFAULT_CXX_STDLIB=libstdc++
-DLLVM_BINUTILS_INCDIR=/home/linuxbrew/.linuxbrew/opt/binutils/include -DLLVM_ENABLE_FFI=ON
-DFFI_INCLUDE_DIR=/home/linuxbrew/.linuxbrew/opt/libffi/lib/libffi-3.2.1/include -DFFI_LIBRARY_DIR=/home/linuxbrew/.linuxbrew/opt/libffi/lib
```
Alright; here are the flags that are currently passed to cmake.

**Comment by iMichka** [comment] 2018-08-07 21:43
Link to previous discussion: https://github.com/Linuxbrew/homebrew-core/pull/7571

**Comment by iMichka** [comment] 2018-08-07 22:15
> ➜  homebrew-core git:(master) /home/linuxbrew/.linuxbrew/bin/llc --version
LLVM (http://llvm.org/):
  LLVM version 6.0.1
  DEBUG build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: haswell

Ok, there is definitely something wrong here.

**Comment by iMichka** [comment] 2018-08-08 20:26
```
g++-5 called with:
-D_GNU_SOURCE
-D__STDC_CONSTANT_MACROS
-D__STDC_FORMAT_MACROS
-D__STDC_LIMIT_MACROS
-I/tmp/llvm-20180808-20094-18y6m3o/lib/MC
-I/tmp/llvm-20180808-20094-1pdujrg/llvm-6.0.1.src/lib/MC
-I/home/linuxbrew/.linuxbrew/include/libxml2
-I/tmp/llvm-20180808-20094-18y6m3o/include
-I/tmp/llvm-20180808-20094-1pdujrg/llvm-6.0.1.src/include
-fPIC
-fvisibility-inlines-hidden
-Werror=date-time
-std=c++11
-Wall
-W
-Wno-unused-parameter
-Wwrite-strings
-Wcast-qual
-Wno-missing-field-initializers
-pedantic
-Wno-long-long
-Wno-maybe-uninitialized
-Wdelete-non-virtual-dtor
-Wno-comment
-ffunction-sections
-fdata-sections
-DNDEBUG

superenv removed: 
-Werror=date-time
-Wall
-W
-Wwrite-strings
-Wcast-qual
-pedantic
-Wdelete-non-virtual-dtor

superenv added:
-pipe
-w
-Os
-isystem/home/linuxbrew/.linuxbrew/include
-I/home/linuxbrew/.linuxbrew/opt/isl@0.18/include
```

**Comment by iMichka** [comment] 2018-08-08 20:41
Some documentation:
https://github.com/llvm-mirror/llvm/blob/master/docs/GettingStarted.rst#compiling-the-llvm-suite-source-code
https://llvm.org/docs/Packaging.html

**Comment by iMichka** [comment] 2018-08-08 20:45
Looking at the documentation, if we ask it to build with `-DCMAKE_BUILD_TYPE=Release`, it should add -03 by default:

> For these builds, the build system will compile the tools and libraries with optimizations enabled and not generate debug info. CMakes default optimization level is -O3. This can be configured by setting the CMAKE_CXX_FLAGS_RELEASE variable on the CMake command line.

But it does not attempt to do so.

**Comment by iMichka** [comment] 2018-08-08 21:28
Looking at what debian does, see the rules file in:
http://http.debian.net/debian/pool/main/l/llvm-toolchain-6.0/llvm-toolchain-6.0_6.0.1-2.debian.tar.xz
> opt_flags = -O2 -DNDEBUG

> -DCMAKE_BUILD_TYPE=RelWithDebInfo \
> -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="$(opt_flags)" \

Another thing worth reading: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=640214

**Comment by iMichka** [comment] 2018-08-08 21:33
The default flags are defined here:
https://github.com/Kitware/CMake/blob/master/Modules/Compiler/GNU.cmake#L43-L47

**Comment by iMichka** [comment] 2018-08-09 20:13
On mac, no optimisation flags are directly added by cmake. Superenv adds `-Os`, which is the same as `-O2`.

Build time on mac with the default `-Os`, for the test file provided:
```
[michkapopoff:~/test] % time clang++ test.cpp -o test  
clang++ test.cpp -o test  0.34s user 0.56s system 90% cpu 0.984 total
[michkapopoff:~/test] % time clang++ test.cpp -o test 
clang++ test.cpp -o test  0.33s user 0.06s system 97% cpu 0.397 total
[michkapopoff:~/test] % time clang++ test.cpp -o test 
clang++ test.cpp -o test  0.31s user 0.05s system 97% cpu 0.376 total
[michkapopoff:~/test] % 
```

**Comment by Char-Aznable** [comment] 2018-08-09 21:17
"-O3" is not necessarily the best but it's what the llvm folks expect: https://llvm.org/docs/GettingStarted.html in a release build. I would not adventure with other options unless the llvm team convince me otherwise.

**Comment by iMichka** [comment] 2018-08-10 17:46
Here is a comparison (on mac):

1) No change to llvm, `-Os` is added by brew
[michkapopoff:~/test] % time clang++ test.cpp -o test  
clang++ test.cpp -o test  0.34s user 0.56s system 90% cpu 0.984 total
[michkapopoff:~/test] % time clang++ test.cpp -o test 
clang++ test.cpp -o test  0.33s user 0.06s system 97% cpu 0.397 total
[michkapopoff:~/test] % time clang++ test.cpp -o test 
clang++ test.cpp -o test  0.31s user 0.05s system 97% cpu 0.376 total
[michkapopoff:~/test] % 

2) With ENV.O3 added to the llvm formula,  `-O3` is added by brew
⌂79% [michkapopoff:~/test] % time clang++ test.cpp -o test  
clang++ test.cpp -o test  0.32s user 0.06s system 95% cpu 0.394 total
⌂79% [michkapopoff:~/test] % time clang++ test.cpp -o test  
clang++ test.cpp -o test  0.31s user 0.10s system 96% cpu 0.429 total
⌂79% [michkapopoff:~/test] % time clang++ test.cpp -o test

I will do the same benchmark on Linux.

> "-O3" is not necessarily the best but it's what the llvm folks expect:

They do not really say that they expect this. They just tell what cmake sets as default. But I am confused because I do not see cmake doing this in practice: the code sets -03, right (
https://github.com/Kitware/CMake/blob/master/Modules/Compiler/GNU.cmake#L43-L47), but this flag is not passed to our superenv shim. I need to understand why.

**Comment by Char-Aznable** [comment] 2018-08-10 21:03
When I said "expect", I didn't mean they require it but I meant they think that is what most likely to happen and I bet that's what they routinely use in their test too, which is something I think wise to follow because it's extremely painful to reason with a compiler if anything goes wrong. I really don't see a good reason not to use '-O2'.

I understand your concern, I see the history of the llvm.rb formula and I found that CMAKE_CXX_FLAGS were turned on and then turned off in different revisions so it might be related to something internal of linuxbrew then (as you expect) and I'm not sure how I should help.

**Comment by iMichka** [comment] 2018-08-11 08:48
I am making progress, I ran the same test on Linux (different computer, so do not compare the absolute values between mac and linux):

1. No change to llvm, -Os is added by brew
```
➜  test time clang++ test.cpp -o test
clang++ test.cpp -o test  0,17s user 0,03s system 74% cpu 0,279 total
➜  test time clang++ test.cpp -o test  
clang++ test.cpp -o test  0,16s user 0,02s system 99% cpu 0,186 total
➜  test time clang++ test.cpp -o test  
clang++ test.cpp -o test  0,17s user 0,01s system 99% cpu 0,179 total
```

2. With ENV.O3 added to the llvm formula, -O3 is added by brew
```
➜  test time clang++ test.cpp -o test
clang++ test.cpp -o test  1,63s user 0,03s system 96% cpu 1,714 total
➜  test time clang++ test.cpp -o test  
clang++ test.cpp -o test  1,62s user 0,02s system 99% cpu 1,643 total
➜  test time clang++ test.cpp -o test  
clang++ test.cpp -o test  1,63s user 0,01s system 99% cpu 1,640 total
```

I can clearly reproduce the problem on Linux, but not on mac.

Conclusion:
Setting 03 on Mac or Linux manually in the formula gives good performance as expected
Letting brew set 0s gives good performance on mac, and bad performance on Linux

I have two possible explanations:
- on mac LLVM is used to build brew's LLVM, on Linux we use gcc5, which may behave diferently
- `Os` behaves differently when building with gcc; compared to LLVM

Maybe there is a more general problem with `Os` when used with gcc. I need to read the doc for these flags more carefully. If that is the case, we may set -02 (like debian does, and what they do on mac because for them Os = 02). This may solve our problems. This may also be an explanation why some of our builds take ages.

**Comment by iMichka** [comment] 2018-08-11 09:35
Here is the documentation about the gcc flags:
https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

For llvm it is a little bit more complicated, but the content of each flag can be fetched like this:
> llvm-as < /dev/null | opt -O2 -disable-output -debug-pass=Arguments
> echo 'int;' | clang -xc -O1 - -o /dev/null -\#\#\#

I also stumbled overs this article, which is a little bit older (2013), but we are building with gcc5; so it may still hold. As Debian recommends and still uses `-O2` ad not `-Os`, it would make sense:
https://lwn.net/Articles/534735/

The last test I want to do is that I am currently building llvm on Linux with `-O2`. I want to see the performance vs `-O3` (it is probably equivalent). I want also to see the size of the bottle. If it is not too big, I think I would recommend we switch to `-O2` for all our builds on Linux.

**Comment by iMichka** [comment] 2018-08-11 10:26
Here is the result with `-O2` on Linux, which are similar to `-O3`
```
➜  test time clang++ test.cpp -o test  
clang++ test.cpp -o test  0,17s user 0,02s system 99% cpu 0,189 total
➜  test time clang++ test.cpp -o test  
clang++ test.cpp -o test  0,18s user 0,02s system 99% cpu 0,194 total
➜  test time clang++ test.cpp -o test  
clang++ test.cpp -o test  0,17s user 0,03s system 99% cpu 0,195 total
```
Regarding bottle size: the current bottle is 857M; the bottle compiled with `-O2` is 540M big. Sounds counter intuitive but this is how it is. So switching to `-O2` gives up more speed, and a smaller bottle.

I am going to open a pull request for this right away.

**Comment by iMichka** [comment] 2018-08-16 11:06
This should be fixed now.

**Closed by iMichka** 2018-08-16 11:06 UTC
Labels: help wanted
