### ISSUE TITLE
readline 7.0.3_1 has something wrong with it

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/homebrew-core#2076] opened 2017-03-15 09:53 UTC
I've been getting lots of issues with `readline` 

```
brew test gawk
Testing gawk
==> /home/linuxbrew/.linuxbrew/Cellar/gawk/4.1.4_1/bin/gawk '{ gsub(/Macro/, "Home"); print }' -
/home/linuxbrew/.linuxbrew/Cellar/gawk/4.1.4_1/bin/gawk: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
Error: gawk: failed
<"Homebrew"> expected but was
<"">.
```

Looking into `readline` I noticed something weird, duplicated files?

```
brew ls -v readline

/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/._libhistory.a
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/libhistory.a
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/._libhistory.so
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/libhistory.so
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/._libhistory.so.7
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/libhistory.so.7
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/._libhistory.so.7.0
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/libhistory.so.7.0
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/._libreadline.a
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/libreadline.a
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/._libreadline.so
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/libreadline.so
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/._libreadline.so.7
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/libreadline.so.7
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/._libreadline.so.7.0
/home/linuxbrew/.linuxbrew/Cellar/readline/7.0.3_1/lib/libreadline.so.7.0
```

These are NOT present in the mac version.
```
/usr/local/Cellar/readline/7.0.3_1/lib/libhistory.7.0.dylib
/usr/local/Cellar/readline/7.0.3_1/lib/libhistory.7.dylib
/usr/local/Cellar/readline/7.0.3_1/lib/libhistory.a
/usr/local/Cellar/readline/7.0.3_1/lib/libhistory.dylib
/usr/local/Cellar/readline/7.0.3_1/lib/libreadline.7.0.dylib
/usr/local/Cellar/readline/7.0.3_1/lib/libreadline.7.dylib
/usr/local/Cellar/readline/7.0.3_1/lib/libreadline.a
/usr/local/Cellar/readline/7.0.3_1/lib/libreadline.dylib
```

If i try to build readline from source, it fails because autoconf needs awk and awk is broken because it needs readline!

```
config.status: creating Makefile
awk: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory  config.status: error: could not create Makefile
```

**Comment by maxim-belkin** [comment] 2017-03-15 10:11
duplicate of #2063

**Closed by maxim-belkin** 2017-03-15 10:11 UTC

**Comment by tseemann** [comment] 2017-03-15 11:52
@maxim-belkin thank you - i thought i'd searched but i think i accidently searched science. whoops
