### ISSUE TITLE
Raxml is compiling with incorrect instruction set

### ISSUE THREAD

**Issue by wheelern** [Linuxbrew/homebrew-core#3099] opened 2017-06-30 12:47 UTC
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

Raxml installation (brew install raxml) completes, but chooses the wrong Makefile when compiling. The choices are SSE3 and AVX. My machine can't use AVX, but only the AVX executable is compiled.

    [zamanian@brc6 ~]$ ls /home/linuxbrew/.linuxbrew/Cellar/raxml/8.2.10_1/bin
    raxmlHPC-PTHREADS  raxmlHPC-PTHREADS-AVX 

    [zamanian@brc6 ~]$ grep avx /proc/cpuinfo
    [zamanian@brc6 ~]$ 

I'm not an expert, but I think the problem is that brew/Library/Homebrew/extend/os/linux/hardware/cpu.rb is incorrectly checking for sse3. On Mac, SSE3 instruction capability is checked with something like:

    dyn-197-2:~ nic$ sysctl -a | grep machdep.cpu.features
    machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA 
    CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ 
    DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE 
    POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C

Which returns "SSE3."

On linux - SSE3 capability is informed by "pni," not "SSE3":
    
    [zamanian@brc6 ~]$ grep pni /proc/cpuinfo
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush 
    acpi mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl pni 
    pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm

So

      def features
        @features ||= flags[1..-1].map(&:intern)
      end

      %w[aes altivec avx avx2 lm sse3 ssse3 sse4 sse4_2].each do |flag|
        define_method(flag + "?") { flags.include? flag }

won't check for the correct string.

**Comment by sjackman** [comment] 2017-06-30 16:54
Thanks for raising this issue, @wheelern. Are you interested in submitting a PR to Linuxbrew/brew to resolve the issue?

**Comment by wheelern** [comment] 2017-06-30 17:08
I wish I could. I'm not comfortable enough with Ruby to be confident in editing core files (even if it is as simple as switching "sse3" for "pni"). Sorry, I'm not as helpful as I wish!

**Comment by sjackman** [comment] 2017-07-04 04:15
Try the following untested patch. If it works for you, feel free to submit it as a PR. Can you point to an URL that documents that `pni` is the appropriate flag to test for SSE3?

```diff
diff --git a/Library/Homebrew/extend/os/linux/hardware/cpu.rb b/Library/Homebrew/extend/os/linux/hardware/cpu.rb
index 10d182687..58124d5bc 100644
--- a/Library/Homebrew/extend/os/linux/hardware/cpu.rb
+++ b/Library/Homebrew/extend/os/linux/hardware/cpu.rb
@@ -107,10 +107,14 @@ module Hardware
         @features ||= flags[1..-1].map(&:intern)
       end
 
-      %w[aes altivec avx avx2 lm sse3 ssse3 sse4 sse4_2].each do |flag|
+      %w[aes altivec avx avx2 lm ssse3 sse4 sse4_2].each do |flag|
         define_method(flag + "?") { flags.include? flag }
       end
 
+      def sse3
+        flags.include? "pni"
+      end
+
       def bits
         @bits ||= Utils.popen_read("getconf", "LONG_BIT").chomp.to_i
       end
```

**Comment by sjackman** [comment] 2017-07-06 23:25
Duplicate of https://github.com/Homebrew/homebrew-science/issues/5920
Fixed by https://github.com/Homebrew/brew/pull/2859

**Closed** 2017-07-06 23:25 UTC
Labels: bug, duplicate
