### ISSUE TITLE
util-linux failed to build on CentOS release 6.8 (Final)

### ISSUE THREAD

**Issue by FrederikLauber** [Linuxbrew/homebrew-core#1480] opened 2017-01-05 16:45 UTC
### Bug reports:

https://gist.github.com/77b1a0f23207ffaed1f6e1ba409f5ea5

From what I understand, there is a problem with finding the pam libraries.

Thanks in advance for any help with this problem.

**Comment by maxim-belkin** [comment] 2017-01-05 17:57
Blocked by #1186

**Comment by maxim-belkin** [comment] 2017-01-05 23:34
I looked more closely at the gist-log and now I'm not so sure that the problems you see are due to pam. Please fix the problems identified by running `brew doctor` and try installing again.

**Comment by FrederikLauber** [comment] 2017-01-06 02:38
Hi,

I am not sure that I can fix all the warnings, at least one of the two is due to the way how multiple python versions are handled in CentOS. The second one, I am still tracking to see what adds the LD_Library variable.

Maybe I missread the gist-log but does it not complain about -lpam and -lpam_misc, being unable to find the two?

**Comment by maxim-belkin** [comment] 2017-01-06 02:43
> I am not sure that I can fix all the warnings

you have to. one of the problems is that python is not found. this is probably due to those system oython artifacts. try using alternative location for Linuxbrew.

**Comment by maxim-belkin** [comment] 2017-01-06 02:46
what is your PATH?

**Comment by FrederikLauber** [comment] 2017-01-06 03:12
``echo $PATH
/home/p91/.linuxbrew/sbin:/package/host/localhost/python-2.7/bin:/home/p91/.linuxbrew/bin:/package/host/localhost/python-2.7/bin:/package/host/localhost/gcc-5/bin:/home/p91/.gem/ruby/2.3.0/bin:/package/host/localhost/ruby-2.3.1/bin:/package/host/localhost/php-7.0.5/bin:/package/host/localhost/perlbrew/bin:/package/host/localhost/gnutls-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/var/qmail/bin:/home/p91/bin:/home/p91/bin
``

**Comment by FrederikLauber** [comment] 2017-01-07 08:50
I got the first warning removed by unseting the variable.
Apparently it is set in the setup of my hoster due to their support of toast.

The second warning I am afraid cannot be removed. There are multiple python versions installed and hence there are also multiple-config files.

I also worked on clearing the Path up but it does not change anything in regards to the error I am seeing.

**Comment by maxim-belkin** [comment] 2017-01-07 11:59
To start, remove `/usr/local/bin` and `/usr/local/sbin` from your PATH.
When I asked for PATH I was hoping to get the result of `echo -e ${PATH//:/\\n}`.

**Comment by FrederikLauber** [comment] 2017-01-07 19:06
Hi,

thanks for sticking with me.

Got it to:
``[p91@cygnus ~]$ brew doctor
Your system is ready to brew.``

PATH:
``[p91@cygnus ~]$ echo -e ${PATH//:/\\n}
/home/p91/.linuxbrew/bin
/home/p91/.linuxbrew/sbin
/package/host/localhost/perlbrew/bin
/bin
/usr/bin
/usr/sbin
/sbin
/home/p91/bin
/home/p91/bin
``

But the problem remains

**Comment by maxim-belkin** [comment] 2017-01-07 19:09
@FrederikLauber use three backticks (```) when copy-pasting code

**Comment by maxim-belkin** [comment] 2017-01-07 19:15
can you post gist-logs now?

**Comment by FrederikLauber** [comment] 2017-01-07 19:53
https://gist.github.com/0b0b69b3cca139294fd766e0f7dd74d6

**Comment by maxim-belkin** [comment] 2017-01-08 04:31
Yes, I'm trying to finish up `linux-pam`

**Comment by sjackman** [comment] 2017-01-11 00:37
One possible workaround is to install Linuxbrew in `/home/linuxbrew/.linuxbrew` so that you can use the precompiled binary bottle for `util-linux`.

Does adding `configure --disable-pam` (if such an option exists) to `util-linux` help this issue?

**Comment by FrederikLauber** [comment] 2017-01-13 11:53
```configure --disable-pam``` does not help.

As I am only a user on the machine in question, I cannot switch over to ```/home/linuxbrew/.linuxbrew```

**Comment by sjackman** [comment] 2017-01-13 16:55
You can if you like ask your system administrator to create a `linuxbrew` user account.
You can also try `brew install --force-bottle util-linux`. It may work, but no promises.

**Comment by maxim-belkin** [comment] 2017-01-14 17:35
> ```configure --disable-pam``` does not help.

can you share gist-logs for that build?

**Comment by sjackman** [comment] 2017-01-16 20:02
Note that I haven't check that there is `--disable-pam` or `--without-pam` option. You'll have to check `./configure --help`.

**Comment by carlorosati** [comment] 2017-01-16 21:44
I already found the workaround in https://github.com/Linuxbrew/homebrew-core/issues/1018#issuecomment-261057772

**Comment by sjackman** [comment] 2017-01-16 22:12
For the record, the workaround to compile `util-linux` without PAM is:
```sh
configure --disable-chfn-chsh --disable-login --disable-nologin --disable-su --disable-runuser
```

**Comment by sjackman** [comment] 2017-01-16 22:13
Duplicate of #1018.

**Comment by sjackman** [comment] 2017-01-16 22:14
Another work around is `brew install --force-bottle util-linux`

**Closed by sjackman** 2017-01-16 22:13 UTC
Labels: build-error, duplicate
