### ISSUE TITLE
vim fails to build with `configure: error: cannot compute sizeof (off_t)`

### ISSUE THREAD

**Issue by lparsons** [Linuxbrew/homebrew-core#4580] opened 2017-10-04 21:06 UTC
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [ ] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Attempting to install vim, I get an error in the configure step, `cannot compute sizeof (off_t)`. Logs at: https://gist.github.com/4a9e467ae0cca47b6c0bea7559c79c25

**Comment by iMichka** [comment] 2017-10-12 15:35
Hi. Thanks for reporting this. Seems someone else already had that problem: https://github.com/Linuxbrew/legacy-linuxbrew/issues/847

Not sure what the root cause is though

**Comment by purwarshubh10** [comment] 2017-10-25 09:16
Hi, 
I haved faced same issue in centos 6.6 while upgrading vim to latest version.
I have resolved it by upgrading my gcc to gc 5.5. After that it has installed.

**Comment by iMichka** [comment] 2017-10-25 09:18
Do you remember what the previous gcc was?

**Comment by purwarshubh10** [comment] 2017-10-25 10:23
Hi iMichka,

Yes the previous gcc version was 4.8

**Comment by iMichka** [comment] 2017-10-25 14:26
Thanks. Probably that one is too old to be able to build vim.

I'll close this issue, as there is a workaround. As long as we do not have a CI for centos 6, we can not guarantee that everything will always work or compile correctly. So people will have to rely on workarounds when needed.

**Closed by iMichka** 2017-10-25 14:26 UTC
Labels: build-error
