### ISSUE TITLE
GHC 8.0.1 build failing

### ISSUE THREAD

**Issue by Horta** [Linuxbrew/homebrew-core#1211] opened 2016-11-23 12:46 UTC
```
> brew install ghc
==> Downloading https://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-src.tar.xz
```

https://gist.github.com/Horta/97fa0dbe622676855bf0100bc20bb590

**Comment by rwhogg** [comment] 2016-11-23 16:03
Hello @Horta. This is a duplicate of https://github.com/Linuxbrew/homebrew-core/issues/851

Nevertheless, thank you for submitting the problem to Linuxbrew 😸

**Closed by rwhogg** 2016-11-23 16:03 UTC
Labels: build-error, duplicate

**Comment by sjackman** [comment] 2016-11-23 18:02
The workaround is
```sh
brew install https://raw.githubusercontent.com/Linuxbrew/homebrew-core/6e4d8edba1f5d3a1aa796559d9bc3d7bdf1024cd/Formula/ghc.rb
```
https://github.com/Linuxbrew/homebrew-core/issues/851#issuecomment-252126769

**Comment by Horta** [comment] 2016-11-23 19:07
That is what I got:

```
> brew install https://raw.githubusercontent.com/Linuxbrew/homebrew-core/6e4d8edba1f5d3a1aa796559d9bc3d7bdf1024cd/Formula/ghc.rb                                                                                                                                                                                
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

######################################################################## 100.0%
==> Downloading https://downloads.haskell.org/~ghc/7.10.3/ghc-7.10.3b-src.tar.bz2
######################################################################## 100.0%
==> Downloading http://ftpmirror.gnu.org/gmp/gmp-6.1.0.tar.bz2
Already downloaded: /homes/horta/.cache/Homebrew/ghc--gmp-6.1.0.tar.bz2
==> ./configure --prefix=/nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/7.10.3b/libexec/integer-gmp --with-pic --disable-shared
==> make
==> make check
==> make install
==> Downloading http://downloads.haskell.org/~ghc/7.6.3/ghc-7.6.3-x86_64-unknown-linux.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/tmp/ghc-20161123-2950-12nz171/ghc-7.10.3/binary --with-gmp-includes=/nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/7.10.3b/libexec/integer-gmp/include --with-gmp-libraries=/nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/7.10.3b/libexec/integer-gmp/lib --with-ld=ld --with-gcc=gcc
==> make install
==> ./configure --prefix=/nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/7.10.3b --with-gmp-includes=/nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/7.10.3b/libexec/integer-gmp/include --with-gmp-libraries=/nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/7.10.3b/libexec/integer-gmp/lib --with-ld=ld --with-gcc=gcc
==> make
==> make install
==> /nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/7.10.3b/bin/ghc-pkg recache
Last 15 lines from /homes/horta/.cache/Homebrew/Logs/ghc/post_install.01.ghc-pkg:
2016-11-23 18:31:30 +0000

/nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/7.10.3b/bin/ghc-pkg
recache

/nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/7.10.3b/lib/ghc-7.10.3/bin/ghc-pkg: error while loading shared libraries: libncursesw.so.6: cannot open shared object file: No such file or directory
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall ghc`
==> Summary  /nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/7.10.3b: 5,446 files, 935.2M, built in 17 minutes 49 seconds
```

Looks like that is just another issue, maybe related to the way I tried to install...

**Comment by sjackman** [comment] 2016-11-23 19:20
A hack workaround is to create a symlink from your `ncurses` library to `libncursesw.so.6` in the `$(brew --prefix)/lib` directory. `brew linkage ghc` can help you troubleshoot. Once you've done that, try `brew postinstall ghc`

**Comment by Horta** [comment] 2016-11-23 19:27
```
horta@hh-yoda-11-01 ~> ls /lib/ | grep libncursesw
horta@hh-yoda-11-01 ~> ls /lib64/ | grep libncursesw
libncursesw.so
libncursesw.so.5
libncursesw.so.5.9
horta@hh-yoda-11-01 ~> echo (brew --prefix)/lib
/nfs/software/stegle/syst3m/linuxbrew/lib
horta@hh-yoda-11-01 ~> ls /nfs/software/stegle/syst3m/linuxbrew/lib | grep libncursesw
libncursesw.a
libncursesw_g.a
libncursesw.so
libncursesw.so.6
libncursesw.so.6.0
horta@hh-yoda-11-01 ~> ls /nfs/software/stegle/syst3m/linuxbrew/lib/libncursesw.so.6
/nfs/software/stegle/syst3m/linuxbrew/lib/libncursesw.so.6@
horta@hh-yoda-11-01 ~> ls -l /nfs/software/stegle/syst3m/linuxbrew/lib/libncursesw.so.6
lrwxrwxrwx 1 horta stegle-group 44 Nov 15 05:55 /nfs/software/stegle/syst3m/linuxbrew/lib/libncursesw.so.6 -> ../Cellar/ncurses/6.0_2/lib/libncursesw.so.6*
horta@hh-yoda-11-01 ~> ls -la /nfs/software/stegle/syst3m/linuxbrew/Cellar/ncurses/6.0_2/lib/libncursesw.so.6
lrwxrwxrwx 1 horta stegle-group 18 Oct 18 13:07 /nfs/software/stegle/syst3m/linuxbrew/Cellar/ncurses/6.0_2/lib/libncursesw.so.6 -> libncursesw.so.6.0*
horta@hh-yoda-11-01 ~> ls -la /nfs/software/stegle/syst3m/linuxbrew/Cellar/ncurses/6.0_2/lib/libncursesw.so.6.0
-rwxr-xr-x 1 horta stegle-group 390726 Oct 18 13:07 /nfs/software/stegle/syst3m/linuxbrew/Cellar/ncurses/6.0_2/lib/libncursesw.so.6.0*
horta@hh-yoda-11-01 ~> brew postinstall ghc
==> /nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/8.0.1/bin/ghc-pkg recache
Last 15 lines from /homes/horta/.cache/Homebrew/Logs/ghc/post_install.01.ghc-pkg:
2016-11-23 19:26:05 +0000

/nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/8.0.1/bin/ghc-pkg
recache


READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues
```

**Comment by Horta** [comment] 2016-11-23 19:29
Not sure if I understood correctly but I don't have privileges to do anything in /lib and /lib64.

Also, ``ls $LD_LIBRARY_PATH | grep libncurses`` does not find anything.

**Comment by sjackman** [comment] 2016-11-23 19:40
For debugging try
```sh
brew linkage ghc
ldd /nfs/software/stegle/syst3m/linuxbrew/Cellar/ghc/8.0.1/bin/ghc-pkg
```
Try
```sh
LD_LIBRARY_PATH=`brew --prefix ncurses`/lib brew postinstall ghc
```
