### ISSUE TITLE
Upgrading guile 2.2.4 -> 2.2.4_1 fails

### ISSUE THREAD

**Issue by root42** [Linuxbrew/homebrew-core#11230] opened 2019-01-15 15:48 UTC
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/fa078bc334967610864149744b283ac4

To help us debug your issue please explain:
- What you were trying to do (and why)

I tried to upgrade my brew installation

- What happened (include command output)

Brew fails:
```
==> Installing guile                                                                      
==> Downloading https://ftp.gnu.org/gnu/guile/guile-2.2.4.tar.xz                          
######################################################################## 100.0%           
==> ./configure --prefix=/HOME/arne_schmitz/linuxbrew/.linuxbrew/Cellar/guile/2
==> make install                                                                          
Error: An exception occurred within a child process:                                      
  Utils::InreplaceError: inreplace failed                                   :     7      ,
/HOME/arne_schmitz/linuxbrew/.linuxbrew/Cellar/guile/2.2.4_1/lib/pkgconfig/guil
e-2.2.pc:                                                                                 
  expected replacement of #<Pathname:/HOME/arne_schmitz/linuxbrew/.linuxbrew/Ce
llar/libffi/3.2.1> with #<Pathname:/HOME/arne_schmitz/linuxbrew/.linuxbrew/opt/
libffi>                                                                                   
```
- What you expected to happen

Expected guile to upgrade without problems

- Step-by-step reproduction instructions (by running `brew install` commands)

brew update 
brew upgrade

**Comment by iMichka** [comment] 2019-01-15 20:20
Hi. I can not reproduce this error. I just pushed a new bottle for `guile`,  see #11205.

Could you maybe try to reinstall this with the `-sd` flag? It will stop the build at the error, and let us investigate.
Could you have a look at the content of the `/HOME/arne_schmitz/linuxbrew/.linuxbrew/Cellar/guile/2.2.4_1/lib/pkgconfig/guil
e-2.2.pc` file?

**Comment by root42** [comment] 2019-01-16 10:53
I did the `-sd` and it stopped as you said.

I also checked the pc file:

```
Libs.private:  /HOME/arne_schmitz/linuxbrew/.linuxbrew/opt/gmp/lib/libgmp.so -Wl,-rpath -Wl,/HOME/arne_schmitz/linuxbrew/.linuxbrew/opt/gmp/lib -lltdl -L/home/linuxbrew/.linuxbrew/Cellar/libffi/3.2.1/lib/../lib -lffi  \
  -lunistring -lcrypt  -lm
```

This is the line which refers to libffi. It shows the /home/linuxbrew path. Since I don't have root permissions on the machine in question, I had to install linuxbrew in my own home directory. Could this be the problem here?

**Comment by iMichka** [comment] 2019-01-18 18:24
I installed brew in a separate folder (not in the standard /home/linuxbrew  path), and even then I could not reproduce this.

Can you check the .pc file before it fails?
For this just add a `raise` in the guile formula before the inreplace, and run the build again in debugging mode with the `-d` flag. Once the exception is raised you can have a look at the file.

Also, can you post your `brew config` and `brew doctor`.

Is there any leftover in `/home/linuxbrew/`. I do not understand how you could have that path written in the file. There may be a big mixup on your setup.

**Comment by iMichka** [comment] 2019-01-27 22:08
Closing here as I can really not reproduce this. You will need to debug this by yourself, sorry about that.

**Closed by iMichka** 2019-01-27 22:08 UTC
Labels: bug, user configuration
