### ISSUE TITLE
gcc 5.5.0_2 - "C compiler cannot create executables"

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/homebrew-core#6628] opened 2018-03-15 04:52 UTC
```
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln works... yes
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... gawk
checking for libatomic support... yes
checking for libcilkrts support... yes
checking for libitm support... yes
checking for libsanitizer support... yes
checking for libvtv support... yes
checking for gcc... gcc-5
checking for C compiler default output file name...
configure: error: in `/tmp/gcc-20180315-115021-3mreup/gcc-5.5.0/build':
configure: error: C compiler cannot create executables
See `config.log' for more details.
```

```
HOMEBREW_VERSION: 1.5.8-4-g0f5ae03
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 0f5ae033947394bd52e166902e8c74cc9cf12780
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: f839d941dbeb8ef73d27bd093eb9107551767c58
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_ARCHFLAGS:
HOMEBREW_BINTRAY_USER: tseemann
HOMEBREW_CACHE: /home/linuxbrew/.cache/Homebrew
HOMEBREW_CC: gcc-5
HOMEBREW_CCCFG:
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CXX: g++-5
HOMEBREW_DEPENDENCIES: zlib,glibc,gmp,mpfr,libmpc,isl
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_DYNAMIC_LINKER: /home/linuxbrew/.linuxbrew/lib/ld.so
HOMEBREW_ERROR_PIPE: /tmp/homebrew20180315-111343-y5dedt/socket
HOMEBREW_FORMULA_PREFIX: /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_2
HOMEBREW_GITHUB_USER: tseemann
HOMEBREW_ISYSTEM_PATHS: /home/linuxbrew/.linuxbrew/include
HOMEBREW_LIBRARY_PATHS: /home/linuxbrew/.linuxbrew/lib
HOMEBREW_OPT: /home/linuxbrew/.linuxbrew/opt
HOMEBREW_OPTFLAGS:
HOMEBREW_OPTIMIZATION_LEVEL: Os
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew
HOMEBREW_RPATH_PATHS: /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_2/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/zlib/lib:/home/linuxbrew/.linuxbrew/opt/glibc/lib:/home/linuxbrew/.linuxbrew/opt/gmp/lib:/home/linuxbrew/.linuxbrew/opt/mpfr/lib:/home/linuxbrew/.linuxbrew/opt/libmpc/lib:/home/linuxbrew/.linuxbrew/opt/isl/lib
HOMEBREW_RUBY_WARNINGS: -W0
HOMEBREW_TEMP: /tmp
```

**Comment by mdotasia** [comment] 2018-03-15 13:56
Same package, different error:

```bash
Already downloaded: /home/thilo/.cache/Homebrew/gcc-5.5.0.tar.xz
==> ../configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_2  --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/home
==> make
Last 15 lines from /home/thilo/.cache/Homebrew/Logs/gcc/02.make:
          ^
In file included from ../../gcc/graphite-interchange.c:30:0:
/home/linuxbrew/.linuxbrew/opt/isl/include/isl/map.h:46:10: note: declared here
 unsigned isl_map_n_out(__isl_keep const isl_map *map);
          ^
rm gcc.pod
make[3]: Leaving directory '/tmp/gcc-20180315-21572-15vingz/gcc-5.5.0/build/gcc'
Makefile:4371: recipe for target 'all-stage1-gcc' failed
make[2]: *** [all-stage1-gcc] Error 2
make[2]: Leaving directory '/tmp/gcc-20180315-21572-15vingz/gcc-5.5.0/build'
Makefile:21079: recipe for target 'stage1-bubble' failed
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory '/tmp/gcc-20180315-21572-15vingz/gcc-5.5.0/build'
Makefile:902: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by peterwc** [comment] 2018-03-15 20:39
It's good to know it's not just me. Similar issue with installing the hello package. 
```
Last 15 lines from /home/henk/.cache/Homebrew/Logs/gcc/02.make:
   return PBB_NB_SCATTERING_TRANSFORM (pbb) / 2;
          ^
/bin/bash ../../gcc/../move-if-change tmp-automata.c insn-automata.c
echo timestamp > s-automata
/bin/bash ../../gcc/../move-if-change tmp-attrtab.c    insn-attrtab.c
/bin/bash ../../gcc/../move-if-change tmp-dfatab.c     insn-dfatab.c
/bin/bash ../../gcc/../move-if-change tmp-latencytab.c insn-latencytab.c
echo timestamp > s-attrtab
rm gcc.pod
make[3]: Leaving directory `/tmp/gcc-20180315-2528-1e5uh05/gcc-5.5.0/build/gcc'
make[2]: *** [all-stage1-gcc] Error 2
make[2]: Leaving directory `/tmp/gcc-20180315-2528-1e5uh05/gcc-5.5.0/build'
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory `/tmp/gcc-20180315-2528-1e5uh05/gcc-5.5.0/build'
make: *** [all] Error 2
```

**Comment by Mystfit** [comment] 2018-03-16 00:42
@peterwc I think I have the same problem. My travis builds were using the gcc-5.5.0_1 bottle which doesn't seem to want to download anymore and gcc compiling from source gives me a similar error.

`==> Installing gcc
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-5.5.0/gcc-5.5.0.tar.xz
==> ../configure --with-native-system-header-dir=/home/linuxbrew/.linuxbrew/incl
==> make
Last 15 lines from /home/travis/.cache/Homebrew/Logs/gcc/02.make:
   return PBB_NB_SCATTERING_TRANSFORM (pbb) / 2;
          ^
../../gcc/graphite-poly.h:377:74: warning: ‘unsigned int isl_map_n_out(const isl_map*)’ is deprecated (declared at /home/linuxbrew/.linuxbrew/opt/isl/include/isl/map.h:46) [-Wdeprecated-declarations]
 #define PBB_NB_SCATTERING_TRANSFORM(PBB) (isl_map_n_out (PBB->transformed))
                                                                          ^
../../gcc/graphite-poly.h:532:10: note: in expansion of macro ‘PBB_NB_SCATTERING_TRANSFORM’
   return PBB_NB_SCATTERING_TRANSFORM (pbb) / 2;
          ^
rm gcc.pod
make[3]: Leaving directory `/tmp/gcc-20180315-14605-scgrqv/gcc-5.5.0/build/gcc'
make[2]: *** [all-stage1-gcc] Error 2
make[2]: Leaving directory `/tmp/gcc-20180315-14605-scgrqv/gcc-5.5.0/build'
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory `/tmp/gcc-20180315-14605-scgrqv/gcc-5.5.0/build'
make: *** [all] Error 2`

**Comment by tseemann** [comment] 2018-03-16 03:50
I can't build any C packages anymore.

**Comment by sjackman** [comment] 2018-03-16 05:07
I'm looking into it.

**Comment by sjackman** [comment] 2018-03-16 05:11
Here's the relevant bug PR for those that wish to follow it: https://github.com/Linuxbrew/homebrew-core/pull/6622

**Comment by sjackman** [comment] 2018-03-16 05:36
Fixed by https://github.com/Linuxbrew/homebrew-core/pull/6632

**Closed by sjackman** 2018-03-16 05:36 UTC
Labels: bug

**Comment by mdotasia** [comment] 2018-03-16 13:42
For me it starts the make script, but after a couple of minutes I get this error:

```
Last 15 lines from /home/thilo/.cache/Homebrew/Logs/gcc/02.make:
../../gcc/c/Make-lang.in:71: recipe for target 'cc1' failed
make[3]: *** [cc1] Error 1
collect2: error: ld returned 1 exit status
../../gcc/cp/Make-lang.in:99: recipe for target 'cc1plus' failed
make[3]: *** [cc1plus] Error 1
rm gfortran.pod gcc.pod
make[3]: Leaving directory '/tmp/gcc-20180316-22483-1v1m9mm/gcc-5.5.0/build/gcc'
Makefile:4450: recipe for target 'all-stage3-gcc' failed
make[2]: *** [all-stage3-gcc] Error 2
make[2]: Leaving directory '/tmp/gcc-20180316-22483-1v1m9mm/gcc-5.5.0/build'
Makefile:21352: recipe for target 'stage3-bubble' failed
make[1]: *** [stage3-bubble] Error 2
make[1]: Leaving directory '/tmp/gcc-20180316-22483-1v1m9mm/gcc-5.5.0/build'
Makefile:902: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sjackman** [comment] 2018-03-16 17:17
@mdotasia `brew update` should resolve this issue. `gcc` has a relocatable bottle, and so does not need to be compiled from source.

**Comment by sjackman** [comment] 2018-03-16 17:28
There was a short regression due to #6636, #6637, and #6644. It's resolved now.

**Comment by mdotasia** [comment] 2018-03-16 18:55
Now it worked, thanks!
