### ISSUE TITLE
portmidi

### ISSUE THREAD

**Issue by maxolasersquad** [Linuxbrew/homebrew-core#1416] opened 2016-12-28 20:52 UTC
portmidi is not installable. It looks like the instructions are currently OSX specific. This is a requirement for mame, which causes it to not build as well.

```
$ brew gist-logs portmidi
https://gist.github.com/68e92c9c8bde08f1380dda4131815463
```

**Comment by rwhogg** [comment] 2016-12-28 23:17
This is a duplicate of #796.

@maxolasersquad, I started a PR #857 to try and fix the `portmidi` build, but unfortunately I'm stuck and don't have time to resolve the remaining issues with it. If you're so inclined, you're welcome to pick up where I left off and see if you can fix the remaining problems.

Thanks!

**Closed by rwhogg** 2016-12-28 23:17 UTC
Labels: duplicate

**Comment by maxolasersquad** [comment] 2016-12-28 23:23
Ugh, I searched the old issue tracker. If I find time I'll see if I can work off your OR for a resolution.
