### ISSUE TITLE
help plz

### ISSUE THREAD

**Issue by alexstaj** [Linuxbrew/homebrew-core#3306] opened 2017-07-18 18:44 UTC
```
tha@bioinfo:~$ brew update
Updated 2 taps (homebrew/science, homebrew/core).
==> Updated Formulae
cmark-gfm                                homebrew/science/beast2
faas-cli                                 homebrew/science/opencollada
flow                                     mariadb
gnatsd                                   mycli
heroku                                   orientdb
homebrew/science/adapterremoval          sourcekitten
Error: stack level too deep
/usr/lib/ruby/2.3.0/pathname.rb:40:in `chop_basename'
/usr/lib/ruby/2.3.0/pathname.rb:358:in `plus'
/usr/lib/ruby/2.3.0/pathname.rb:350:in `+'
/home/tha/.linuxbrew/Library/Homebrew/formulary.rb:192:in `formula_name_path'
/home/tha/.linuxbrew/Library/Homebrew/formulary.rb:210:in `formula_name_path'
...
/home/tha/.linuxbrew/Library/Homebrew/formulary.rb:210:in `formula_name_path'
/home/tha/.linuxbrew/Library/Homebrew/formulary.rb:184:in `initialize'
/home/tha/.linuxbrew/Library/Homebrew/formulary.rb:355:in `new'
/home/tha/.linuxbrew/Library/Homebrew/formulary.rb:355:in `loader_for'
/home/tha/.linuxbrew/Library/Homebrew/formulary.rb:275:in `factory'
/home/tha/.linuxbrew/Library/Homebrew/formulary.rb:306:in `from_keg'
/home/tha/.linuxbrew/Library/Homebrew/formulary.rb:289:in `from_rack'
/home/tha/.linuxbrew/Library/Homebrew/formula.rb:1383:in `block in installed'
/home/tha/.linuxbrew/Library/Homebrew/formula.rb:1381:in `map'
/home/tha/.linuxbrew/Library/Homebrew/formula.rb:1381:in `installed'
/home/tha/.linuxbrew/Library/Homebrew/cmd/update-report.rb:505:in `migrate_formula_rename'
/home/tha/.linuxbrew/Library/Homebrew/cmd/update-report.rb:101:in `each'
/home/tha/.linuxbrew/Library/Homebrew/cmd/update-report.rb:101:in `update_report'
/home/tha/.linuxbrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by sjackman** [comment] 2017-07-18 23:05
Duplicate of https://github.com/Linuxbrew/brew/issues/430

**Closed by sjackman** 2017-07-18 23:05 UTC
