### ISSUE TITLE
gcc-5.5.0 build failure on Scientific Linux 7

### ISSUE THREAD

**Issue by gipert** [Linuxbrew/homebrew-core#7597] opened 2018-05-09 12:47 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# gcc-5.5.0 build failure on Scientific Linux 7
An evil GithHub Homebrew bot redirected me here :)

I'm trying to `brew install gcc` on a remote server (on which I don't have sudo permissions -> can't fix some problems reported by `brew doctor`) using Linuxbrew (so installed without sudo). The build process fails with the error:
```
[...]
g++-4.8   -g -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H -DGENERATOR_FILE  -o build/genmodes \
    build/genmodes.o build/errors.o ../build-x86_64-unknown-linux-gnu/libiberty/libiberty.a
build/gengenrtl > tmp-genrtl.h
build/gengenrtl: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
[...]
```

Here's the result of [`brew install gcc`](https://gist.github.com/474ada83ed2d24039474edcbe3b2f8ae)
Here's the result of [`brew install gcc --without-glibc`](https://gist.github.com/gipert/b4c62bd2760b2ba5ce35ab0200503d7e)

I don't understand this error because:
```
$ yum list | grep libstdc++
compat-libstdc++-33.x86_64               3.2.3-72.el7               @sl
libstdc++.i686                           4.8.5-16.el7_4.2           @sl-fastbugs
libstdc++.x86_64                         4.8.5-16.el7_4.2           @sl-fastbugs
libstdc++-devel.x86_64                   4.8.5-16.el7_4.2           @sl-fastbugs
compat-libstdc++-33.i686                 3.2.3-72.el7               sl
libstdc++-devel.i686                     4.8.5-16.el7_4.2           sl-fastbugs
libstdc++-docs.x86_64                    4.8.5-16.el7_4.2           sl-fastbugs
libstdc++-static.i686                    4.8.5-16.el7_4.2           sl-fastbugs
libstdc++-static.x86_64                  4.8.5-16.el7_4.2           sl-fastbugs
```
But I'm not that expert... Does this derive from the environment I'm working in (which in any case I can't really modify because I don't have admin rights)?

### steps to reproduce the issue
```
git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew 
export PATH="~/.linuxbrew/bin:$PATH"
export PATH="~/.linuxbrew/sbin::$PATH"
export MANPATH="$(brew --prefix)/share/man:$MANPATH"
export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
brew install gcc
```

**Comment by amdrsantos** [comment] 2018-05-10 10:07
Same problem here!
Any solution found?

**Comment by gipert** [comment] 2018-05-10 10:15
In my case the issue is the same as in #7574, Python cannot compile because of this missing `libstdc++` (which happens only with brew, I can manually compile it). Yesterday I tried to check if this is also the case for gcc but I didn't manage to compile it manually yet :)

**Comment by iMichka** [comment] 2018-05-10 10:39
Can you try to find/locate `libstdc++.so.6` on your system? It should be in the gcc 4.8 subfolder for those who use the systems gcc.

**Comment by gipert** [comment] 2018-05-10 13:18
```
$ find /usr/lib -name *libstdc++*                                                                                       []
/usr/lib/libstdc++.so.6.0.19
/usr/lib/gcc/x86_64-redhat-linux/4.8.2/32/libstdc++.a
/usr/lib/gcc/x86_64-redhat-linux/4.8.2/32/libstdc++.so
/usr/lib/gcc/x86_64-redhat-linux/4.8.2/libstdc++.so
/usr/lib/libstdc++.so.6
```

**Comment by amdrsantos** [comment] 2018-05-10 13:36
`find ~/.linuxbrew/ -name libstdc++*` with no results

**Comment by iMichka** [comment] 2018-05-10 13:38
@gipert I confirm what you are seeing in interactive mode (on ubuntu 16.04). Though I can find the libraries with:
```
linuxbrew@51b37e63aeba:/tmp/gcc-20180510-18025-y8lsoq/gcc-5.5.0$ find /usr/lib -name *.so* | grep c++
/usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.so
/usr/lib/x86_64-linux-gnu/libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
```

Maybe some "find" weirdness at play. But the files are there.

**Comment by gipert** [comment] 2018-05-10 13:42
wtf, you're right:
```shell
lfs2:gcc-5.5.0 $ find /usr/lib -name *.so* | grep c++
/usr/lib/libstdc++.so.6.0.19
/usr/lib/gcc/x86_64-redhat-linux/4.8.2/32/libstdc++.so
/usr/lib/gcc/x86_64-redhat-linux/4.8.2/libstdc++.so
/usr/lib/libstdc++.so.6
```
Still then I don't understand why it can't be found at compile time, I'll try to explicitly set the location during the configure step

**Comment by iMichka** [comment] 2018-05-10 13:47
Running `.configure --help` and reading the doc:
```
LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
LIBS        libraries to pass to the linker, e.g. -l<library>
CPPFLAGS    C/C++/Objective C preprocessor flags, e.g. -I<include dir> if
              you have headers in a nonstandard directory <include dir>
```
I guess you may try to set some of these env variables in the the formula and see if helps.

**Comment by gipert** [comment] 2018-05-10 14:39
I tried with:
```
LDFLAGS="-L/usr/lib"
CPPFLAGS="-L/usr/lib"
LIBS="-l/usr/lib/libstdc++.so.6"
```
but no way...

**Comment by gipert** [comment] 2018-05-10 15:18
This fails too, but for a different (?) reason:
```dockerfile
FROM scientificlinux/sl:7

RUN yum install -y curl make ruby sudo which gcc \
  && yum clean all

RUN useradd -m -s /bin/bash linuxbrew \
	&& echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

USER linuxbrew
WORKDIR /home/linuxbrew

ENV PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH \
	SHELL=/bin/bash \
	USER=linuxbrew

RUN yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)" \
	&& brew install gcc && brew uninstall gcc && HOMEBREW_MAKE_JOBS=1 brew install --verbose --build-from-source gcc
```
```
configure: error: error verifying int64_t uses long long
make[2]: *** [configure-stage1-gcc] Error 1
make[2]: Leaving directory `/tmp/gcc-20180510-31883-19rzuc0/gcc-5.5.0/build'
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory `/tmp/gcc-20180510-31883-19rzuc0/gcc-5.5.0/build'
make: *** [all] Error 2
```

**Comment by ebzheng** [comment] 2018-05-10 20:17
I have materially the same issue that appeared during a batch of `brew upgrades` Tuesday, on RHEL Server 7.2 (Maipo). I was also reconfiguring my environment at the time, so I assumed I had broken something myself...

Unusually, if this is some flavor of regression, rolling back the formula to `3b1bfc9` (Apr 4) doesn't resolve the issue.

**Comment by iMichka** [comment] 2018-05-11 19:16
Actually `ENV["PATH"]` is set to `/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/opt/m4/bin:/usr/bin:/bin:/usr/sbin:/sbin` in the `cc` shim. So this is fine.

The actual error is:
`g++-4.8:374:in `exec': No such file or directory - g++-4.8 (Errno::ENOENT)`

The problem is that `ls -l $(brew --prefix)/bin/` shows only gcc-4.8; and `g++-4.8` is missing.
`/usr/bin/ only contains `gcc`, and no `g++`, so one of the compilers is missing ...

**Comment by gipert** [comment] 2018-05-11 19:49
You mean the symlink to `g++` is missing?

**Comment by iMichka** [comment] 2018-05-11 19:51
No, g++ was completely missing, because the `gcc-c++` package needs to be installed.

Here is an updated Dockerfile with the `gcc-c++` package:
```
FROM scientificlinux/sl:7

RUN yum install -y curl make ruby sudo which gcc gcc-c++\
  && yum clean all

RUN useradd -m -s /bin/bash linuxbrew \
	&& echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

USER linuxbrew
WORKDIR /home/linuxbrew

ENV PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH \
	SHELL=/bin/bash \
	USER=linuxbrew

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" \
    && brew config

RUN HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc --without-glibc
```

Making progress, it compiles `gmp` now, but fails during the `gcc` compilation with:
`ld: cannot find crti.o: No such file or directory`

**Comment by iMichka** [comment] 2018-05-11 22:15
2 errors that were found and fixed:
- `gcc-c++` was not installed. It needs to be installed before linuxbrew is installed. If it is installed later, `/usr/bin/g++-4.8` needs to be manually symlinked to `/home/linuxbrew/.linuxbrew/bin`.
- `gcc` was failing to find `crti.o`, which is fixed with #7632

I am running a full build in a new docker container to see if this works out.

**Comment by gipert** [comment] 2018-05-11 22:19
Adding `/usr/lib64` to `LD_LIBRARY_PATH` worked for you? I just tried but with no luck

**Comment by tueda** [comment] 2018-05-12 07:13
Same problem here. I'm trying to setup Linuxbrew on SLC 6.9 by following [Install Linuxbrew on CentOS 6 without sudo](https://github.com/Linuxbrew/brew/wiki/CentOS6#install-linuxbrew-on-centos-6-without-sudo). Using workarounds of [`LIBRARY_PATH`](https://github.com/Linuxbrew/homebrew-core/issues/7172#issuecomment-385038469) for `gcc` and `glibc` and [missing GCC spec files](https://github.com/Linuxbrew/homebrew-core/issues/5707#issuecomment-365176629), eventually I come to this issue at the last command `HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc`.

**Comment by iMichka** [comment] 2018-05-12 09:44
Ok so now that #7635 is merged, this works:

```
FROM scientificlinux/sl:7

RUN yum install -y curl make ruby sudo which gcc gcc-c++\
  && yum clean all

RUN useradd -m -s /bin/bash linuxbrew \
	&& echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

USER linuxbrew
WORKDIR /home/linuxbrew

ENV PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH \
	SHELL=/bin/bash \
	USER=linuxbrew

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)" \
    && brew config

# Install brewed gcc 5 to be able to build glibc
RUN HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc --without-glibc
```

Now I am looking at the next steps, which are installing a brewed `glibc`, and recompiling `gcc` against it.

**Comment by gipert** [comment] 2018-05-12 12:31
I confirm that `HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc --without-glibc` now works on my cluster.

I tried, but you may already know that, to `brew install glibc` (had to use workaround in #5707) with the following error:
```
/lfs/l2/gerda/pertoldi/.linuxbrew/opt/binutils/bin/ld: i386 architecture of input file `/lib/crt1.o' is incompatible with i386:x86-64 output
/lfs/l2/gerda/pertoldi/.linuxbrew/opt/binutils/bin/ld: i386 architecture of input file `/lib/crti.o' is incompatible with i386:x86-64 output
/lfs/l2/gerda/pertoldi/.linuxbrew/opt/binutils/bin/ld: i386 architecture of input file `/lib/crtn.o' is incompatible with i386:x86-64 output
/lfs/l2/gerda/pertoldi/.linuxbrew/opt/binutils/bin/ld: /lib/crt1.o: file class ELFCLASS32 incompatible with ELFCLASS64
/lfs/l2/gerda/pertoldi/.linuxbrew/opt/binutils/bin/ld: final link failed: File in wrong format
```

**Comment by iMichka** [comment] 2018-05-12 15:39
@gipert That is a different error. Please open a new issue for that.

Also, please, to all users, this issue is about scientific linux 7. The bug may be more general but please refrain to give details about centos 6 or others, as this may be slightly different. I want to get it working for scientific linux 7 first, we will take care of centos 6 in a second step.

**Comment by gipert** [comment] 2018-05-12 15:43
...the cluster I'm talking about is exactly `Scientific Linux release 7.4 (Nitrogen)`, never worked on CentOS6 so far

**Comment by iMichka** [comment] 2018-05-12 15:44
I found the problem:
https://github.com/Linuxbrew/homebrew-core/commit/3b1bfc9a633de68afc6dc64a5ba5f65c3bb2c6a7

There were some lines in the gcc formula that were removed a few days ago:
```
# Fix for GCC 4.4 and older that do not support -static-libstdc++
# gengenrtl: error while loading shared libraries: libstdc++.so.6
mkdir_p lib
ln_s ["/usr/lib64/libstdc++.so.6", "/lib64/libgcc_s.so.1"], lib
```

This is exactly the error we are seeing. I think it was removed because we do not care about gcc 4.4 anymore. But it seems it is also needed for gcc 4.8 on scientific Linux 7. I am running a new build with that code, and I will see if it helps.

**Comment by iMichka** [comment] 2018-05-12 15:45
> ...the cluster I'm talking about is exactly Scientific Linux release 7.4 (Nitrogen), never worked on CentOS6 so far

The comment was not for you, but for @tueada :)

Nevertheless, thanks you everybody for helping me debugging this. I think we are close to a solution.

**Comment by gipert** [comment] 2018-05-12 16:17
> The comment was not for you, but for @tueada :)

Oups! :)

*We* need to thank you for your dedication to tackle the problem!

**Comment by iMichka** [comment] 2018-05-12 16:53
Ok it worked, can you try this patch: #7643

Normally you just need to use:
`HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc`
on scientific linux 7; because gcc 4.8 is new enough and is able to build glibc directly.

**Comment by gipert** [comment] 2018-05-12 17:40
> 4.8 is new enough and is able to build glibc directly.

Yep, in fact it builds without troubles, however, [`libstdc++.so.6` is still not found](https://gist.github.com/5964c283d4e05c4a162ca412cf8911d6)...

Does it work in the SL7 container?

**Comment by iMichka** [comment] 2018-05-12 17:46
I guess you mean `glibc` build correctly? Nice.

For gcc, this is weird. It worked in the container. Was the symlink from patch #7643 correctly created?

**Comment by gipert** [comment] 2018-05-12 17:48
mmmmh I don't think so...
```shell
$ ls /lib64/libgcc_s.so.1                                                                                            []
lrwxrwxrwx 1 root root 28 Mar 20 07:58 /lib64/libgcc_s.so.1 -> libgcc_s-4.8.5-20150702.so.1*
$ ls /usr/lib64/libstdc++.so.6                                                                                      []
lrwxrwxrwx 1 root root 19 Mar 20 07:58 /usr/lib64/libstdc++.so.6 -> libstdc++.so.6.0.19*
```

**Comment by gipert** [comment] 2018-05-12 17:51
As you see `/usr/lib64/libstdc++.so.6` was already there, created by someone else (so I can't change it), I have to investigate

**Comment by iMichka** [comment] 2018-05-12 17:51
It's the other way round. The symlink is created in a `lib` folder during the build, inside the tmp build dir. Something like `/tmp/gcc*****/5.***/lib`. You may need to adapt that path to find the right location.

**Comment by gipert** [comment] 2018-05-12 18:52
I am stupid, I thought #7643 was already merged! Now everything works fine:
```
$ brew install gcc
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-5.5.0/gcc-5.5.0.tar.xz
Already downloaded: /home/extern/pertoldi/.cache/Homebrew/gcc-5.5.0.tar.xz
==> ../configure --with-isl=/lfs/l2/gerda/pertoldi/.linuxbrew/opt/isl@0.18 --with-bugurl=https://github.com/Linuxbrew/homebrew-cor
==> make
==> make install
==> strip --strip-unneeded --preserve-dates /lfs/l2/gerda/pertoldi/.linuxbrew/Cellar/gcc/5.5.0_4/bin/gcov-5 /lfs/l2/gerda/pertoldi
==> Creating the GCC specs file: /lfs/l2/gerda/pertoldi/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/specs
🍺  /lfs/l2/gerda/pertoldi/.linuxbrew/Cellar/gcc/5.5.0_4: 1,361 files, 164.8MB, built in 28 minutes 30 seconds
```
Finally this issue can be closed, thanks so much for your effort!

**Comment by iMichka** [comment] 2018-05-12 19:10
And merged! Thanks for your patience. Glad we got this sorted out. Have fun with Linuxbrew :)

**Closed by iMichka** 2018-05-12 19:10 UTC
Labels: bug

**Comment by sjackman** [comment] 2018-05-14 22:25
A bit late to the party, but thanks everyone for sorting out this issue!
