### ISSUE TITLE
coreutils: help2man: can't get `--help' info from man/chcon.td/chcon

### ISSUE THREAD

**Issue by tintin42** [Linuxbrew/homebrew-core#425] opened 2016-06-15 13:46 UTC
Fresh standard (not stand alone) install of linuxbrew on RHEL 7. Brew doctor have no complaints.

Seems to fail in the manual generation when brewing stable coreutils 8.25. Tried with help2man via both yum and brew.

```
> ==> ./configure --prefix=/tools/brew/Cellar/coreutils/8.25 --program-prefix=g --without-gmp
> ==> make install
> Last 15 lines from /home/ssi.ad/jlr/.cache/Homebrew/Logs/coreutils/02.make:
>   GEN      man/basename.1
>   GEN      man/cat.1
>   GEN      man/chcon.1
>   GEN      man/chgrp.1
>   GEN      man/chmod.1
>   GEN      man/chown.1
> help2man: can't get `--help' info from man/chcon.td/chcon
> Try`--no-discard-stderr' if option outputs to stderr
>   GEN      man/cksum.1
> make[2]: **\* [man/chcon.1] Error 127
> make[2]: **\* Waiting for unfinished jobs....
> make[2]: Leaving directory `/tmp/coreutils-20160615-26099-1533mmh/coreutils-8.25'
> make[1]: *** [install-recursive] Error 1
> make[1]: Leaving directory`/tmp/coreutils-20160615-26099-1533mmh/coreutils-8.25'
> make: **\* [install] Error 2
```

Complete log:
https://gist.github.com/e0b644c7925f9696905b55a7e3408714

**Comment by sjackman** [comment] 2016-06-17 16:32
Please use triple backticks to quote logs rather than `>`. See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by tintin42** [comment] 2016-06-17 19:28
--force-bottle works in the limited testing I did now, thanks :) Do all/most packages also have prebuilt binaries?
coreutils builds fine in another test I did with a standalone linuxbrew install

**Comment by rwhogg** [comment] 2016-06-17 19:40
> Do all/most packages also have prebuilt binaries?

269 out of 3613 "core" formulae have bottles, including most of the popular ones, and some others (a lot of the Java-based formulae, for example) don't need them. We're working on the rest :smile_cat:

**Comment by sjackman** [comment] 2016-06-17 21:33
I'm glad that the workaround worked. The error is a mystery to me though. I'm going to leave this issue open, in the hopes that someone offers some insight.

I found a hit on Google for it: http://lists.linuxfromscratch.org/pipermail/lfs-support/2014-November/048100.html
My best guess is that it's a Makefile race condition and it may be resolved by:
```sh
HOMEBREW_MAKE_JOBS=1 brew install coreutils
```

**Comment by tintin42** [comment] 2016-06-20 21:25
>```HOMEBREW_MAKE_JOBS=1 brew install coreutils```

Tried to set the variable, but unfortunately the brew fails on the same step, so it might not be a race condition.

**Comment by sjackman** [comment] 2016-06-22 23:07
Sorry I couldn't be of more help.

**Comment by dwaggott** [comment] 2016-11-18 17:02
Similar issue on coreutils install. The binary bottle installed but gives `Illegal Instruction` on many of the commands like `rm` and `mkdir`

```
$ brew install coreutils
------------------------------
You can't use sudo on Sherlock
------------------------------
If you need software installed, please contact
research-computing-support@stanford.edu. 
==> Downloading https://ftpmirror.gnu.org/coreutils/coreutils-8.25.tar.xz
Already downloaded: /home/dwaggott/.cache/Homebrew/coreutils-8.25.tar.xz
==> ./configure --prefix=/home/dwaggott/.linuxbrew/Cellar/coreutils/8.25 --program-prefix=g --without-gmp
==> make install
Last 15 lines from /home/dwaggott/.cache/Homebrew/Logs/coreutils/02.make:
  GEN      man/factor.1
help2man: can't get `--help' info from man/cp.td/cp
Try `--no-discard-stderr' if option outputs to stderr
help2man: can't get `--help' info from man/chcon.td/chcon
Try `--no-discard-stderr' if option outputs to stderr
make[2]: *** [man/chcon.1] Error 127
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [man/cp.1] Error 127
help2man: can't get `--help' info from man/dir.td/dir
Try `--no-discard-stderr' if option outputs to stderr
make[2]: *** [man/dir.1] Error 127
make[2]: Leaving directory `/tmp/coreutils-20161117-47905-pobbjr/coreutils-8.25'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/tmp/coreutils-20161117-47905-pobbjr/coreutils-8.25'
make: *** [install] Error 2
```

**Comment by sjackman** [comment] 2016-11-18 19:55
@dwaggott Please report the output of `brew gist-logs coreutils`

> Illegal Instruction

Which machine/processor are you using?

**Comment by dwaggott** [comment] 2016-11-18 19:59
https://gist.github.com/2588374564ad7523082a0bff46c6df68

```
$ uname -a
Linux masamune 3.19.0-58-generic #64-Ubuntu SMP Thu Mar 17 18:30:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
dwaggott@masamune: /home/dwaggott/projects/hcm/scripts
$ cat /proc/cpuinfo | grep vendor | uniq
vendor_id       : GenuineIntel
dwaggott@masamune: /home/dwaggott/projects/hcm/scripts
$ cat /proc/cpuinfo | grep 'model name' | uniq
model name      : Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
dwaggott@masamune: /home/dwaggott/projects/hcm/scripts
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz
Stepping:              2
CPU MHz:               1600.000
CPU max MHz:           2934.0000
CPU min MHz:           1600.0000
BogoMIPS:              5866.95
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-23
```

**Comment by sjackman** [comment] 2016-11-18 21:59
`brew config` reports `CPU: 32-core 64-bit haswell`. I can't think of any good reason that you should be seeing `Illegal Instruction`. Try getting a backtrace from `gdb` of the core dump.
```sh
ulimit -c unlimited
mkdir foo
# illegal instruction, core dumped
gdb mkdir core.*
bt
x/i $pc
quit
```

**Comment by sjackman** [comment] 2016-11-18 22:02
As for `help2man: can't get '--help' info from man/cp.td/cp`, I'd suggesting reporting the bug upstream to the `coreutils` developers.

**Comment by iMichka** [comment] 2017-09-09 18:47
This issue is almost 1 year old. Since then, corutils has been bumped to version 8.28. I am closing this issue; if you still have trouble with this, please open a new issue and fill out the issue template. Thanks/

**Closed by iMichka** 2017-09-09 18:47 UTC
Labels: build-error, help wanted, upstream

**Comment by JuPlutonic** [comment] 2017-12-26 10:33
Brew install --force-bottle coreutils is the remedy for me now.
I will test it with my home PCs and see if it reproducable...

**Comment by sjackman** [comment] 2019-09-09 17:42
I've just run into this particular error myself.
```
  GEN      man/chcon.1
help2man: can't get `--help' info from man/chcon.td/chcon
Try `--no-discard-stderr' if option outputs to stderr
make[2]: *** [man/chcon.1] Error 127
```
