### ISSUE TITLE
CentOS6 install of gcc --without-glibc fails with crti.o not found

### ISSUE THREAD

**Issue by jhdub23** [Linuxbrew/homebrew-core#7172] opened 2018-04-12 21:07 UTC
I'm trying to install linuxbrew on CentOS6 without sudo,  following the instructions on the [wiki](https://github.com/Linuxbrew/brew/wiki/CentOS6)..  However, it's failing on `brew install gcc --without-glibc`:

    ld: crti.o: No such file: No such file or directory
    collect2: error: ld returned 1 exit status

Commands:

    git clone https://github.com/Linuxbrew/brew.git .linuxbrew_rhel6
    export HOMEBREW_NO_ANALYTICS=1
    export HOMEBREW_NO_AUTO_UPDATE=1
    export HOMEBREW_BUILD_FROM_SOURCE=1
    export PATH=.:/data3/jhwest/work/tmp/.linuxbrew_rhel6/bin:/bin:/usr/bin
    brew tap linuxbrew/xorg
    brew install gcc --without-glibc

Logs are at [gist-logs](https://gist.github.com/b38d614a899ba65868eddc4737ffde3f)

Can anyone suggest a quick fix/workaround?

Checklist is as follows:

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by yinchunxiang** [comment] 2018-04-25 12:06
same problem

**Comment by achen26** [comment] 2018-04-25 21:16
also running into this problem when trying to install filebeat without sudo access

**Comment by jhdub23** [comment] 2018-05-05 00:53
Thank you robxu9.  That worked.

**Comment by sjackman** [comment] 2018-05-05 17:59
Yes, agreed. Instructions to reproduce the issue in a `centos:6` Docker image and a PR to `Linuxbrew/brew` to resolve the issue would be very welcome.

**Comment by sjackman** [comment] 2018-05-05 18:00
@robxu9 Thanks for finding the fix, Robert! Would you like to submit a PR?

**Comment by tueda** [comment] 2018-05-11 04:03
The `LIBRARY_PATH` fix works also on Scientific Linux CERN 6.9, where I got an almost same error `/usr/lib/crti.o: could not read symbols: File in wrong format`.

**Comment by iMichka** [comment] 2018-05-11 20:17
@robxu9 something like this: https://github.com/Linuxbrew/homebrew-core/pull/7632 ?

**Comment by iMichka** [comment] 2018-05-11 22:11
This should be now fixed with #7632, please update and test.

**Comment by tueda** [comment] 2018-05-12 05:26
#7632 doesn't help for me because it finds `/usr/lib/crti.o` instead of the correct one at `/usr/lib64/crti.o`. Could it be OK to give a priority to `/usr/lib64` than `/usr/lib` for others?

**Comment by iMichka** [comment] 2018-05-12 07:32
I don't mind putting the `/usr/lib64` folder first.

So you have two `crti.o` files in two different lib folders? And they are not the same? Which packages did install these files?

**Comment by tueda** [comment] 2018-05-12 07:40
What I see is
```
$ file /usr/lib/crti.o
/usr/lib/crti.o: ELF 32-bit LSB relocatable, Intel 80386, version 1 (SYSV), not stripped
$ file /usr/lib64/crti.o
/usr/lib64/crti.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

I'm not sure how these files were installed because I have no root privilege. I'm also not sure if it is a common practice to have 32 bit files in `/usr/lib` and 64 bit files in `/usr/lib64`. Maybe it's specific to the machine or administrator's customization.

**Comment by iMichka** [comment] 2018-05-12 07:50
Looks funny. Not sure it is common, I am new to all this multi arch stuff on centos ... I would have expected the 32 bit one to be in `/usr/lib32/`.

- Is `/usr/lib` a symlink to something (`/usr/lib32/` or `/usr/lib64/`?).
- Are you on a 32 bit OS?

I need to rewrite he code for the include path to check the arch, and then setup the paths in the right order.

**Comment by iMichka** [comment] 2018-05-12 07:53
I changed the order here: https://github.com/Linuxbrew/homebrew-core/pull/7635

Can you confirm that this change helps for that error?

**Comment by tueda** [comment] 2018-05-12 07:58
Sorry if confusing: I'm not on CentOS but on Scientific Linux (but it should be almost the same, I guess).
```
$ cat /etc/redhat-release
Scientific Linux CERN SLC release 6.9 (Carbon)
$ uname -a
Linux ws01 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
```
I will try your change of #7635. Thanks.

**Comment by tueda** [comment] 2018-05-12 09:15
Indeed the cookbook in #7635 worked to me.

Clean install without root on my environment (SLC 6.9):  the following works:
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
PATH=$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH
HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_BUILD_FROM_SOURCE=1 brew install https://raw.githubusercontent.com/iMichka/homebrew-core-1/47538613258561a89d9b4403f30621d439bb841c/Formula/gcc.rb --without-glibc  # 7635
```

**Comment by iMichka** [comment] 2018-05-12 09:43
Ok, thanks. I merged #7635, and updated all the other gcc formulae using the same code in (#7640).

This fixes building gcc from source with `brew install gcc --without-glibc` on centos and scientific linux.

I am closing this issue, as the initial error is fixed.

If there are other problems with other formulae, please open a new issue.

**Closed by iMichka** 2018-05-12 09:43 UTC
Labels: bug

**Comment by sjackman** [comment] 2018-05-14 22:17
I've never seen `/usr/lib32` on a wild system. On CentOS the two folders are named…
`/usr/lib` for 32-bit libraries
`/usr/lib64` for 64-bit libraries

On Debian and Ubuntu, the two folders are named…
`/usr/lib` for 32-bit libraries
`/usr/lib/x86_64-linux-gnu` for 64-bit libraries

On a theoretical 64-bit non multiarch system, the 64-bit libraries should be named `/usr/lib` and there would be no 32-bit library folder, but I don't know of a common example.

**Comment by glensc** [comment] 2018-05-14 22:34
`/lib32` is afaik used on ubuntu, and `/libx32` is used for [X32_ABI](https://en.wikipedia.org/wiki/X32_ABI) ;)

**Comment by sjackman** [comment] 2018-05-14 22:36
A default installation of Ubuntu does not have a `/lib32` directory. `/libx32` is frightening! 😱
