### ISSUE TITLE
mongo-c-driver: --enable-ssl=darwin doesn't work on Linux

### ISSUE THREAD

**Issue by david9991** [Linuxbrew/homebrew-core#1414] opened 2016-12-28 07:35 UTC
`--enable-ssl=darwin` option won't work on linuxbrew (linux).

**Comment by sjackman** [comment] 2017-01-11 01:05
Hi, David. A pull request to resolve this issue would be welcome.

**Comment by timotheecour** [comment] 2017-01-13 09:21
duplicate of https://github.com/Linuxbrew/homebrew-core/issues/1567

**Closed** 2017-02-14 00:53 UTC
Labels: build-error
