### ISSUE TITLE
install openssl@1.1

### ISSUE THREAD

**Issue by subunits** [Linuxbrew/homebrew-core#1215] opened 2016-11-23 17:16 UTC
Last 15 lines from /home/username/.cache/Homebrew/Logs/openssl@1.1/02.make:

```
/home/username/.linuxbrew/Cellar/perl/5.24.0_2/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
/home/username/.linuxbrew/Cellar/perl/5.24.0_2/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _all
make[1]: Entering directory `/home/username/tmp/openssl@1.1-20161123-14873-1yzi8ju/openssl-1.1.0b'
make[1]: Leaving directory `/home/username/tmp/openssl@1.1-20161123-14873-1yzi8ju/openssl-1.1.0b'
make[1]: Entering directory `/home/username/tmp/openssl@1.1-20161123-14873-1yzi8ju/openssl-1.1.0b'
CC="/home/username/.linuxbrew/bin/gcc-5" /home/username/.linuxbrew/Cellar/perl/5.24.0_2/bin/perl crypto/aes/asm/aes-x86_64.pl macosx crypto/aes/aes-x86_64.s
/home/username/.linuxbrew/bin/gcc-5  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/username/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"/home/username/.linuxbrew/Cellar/openssl@1.1/1.1.0b/lib/engines-1.1\"" -O3 -D_REENTRANT -arch x86_64 -DL_ENDIAN -Wall  -fPIC -MMD -MF crypto/aes/aes-x86_64.d.tmp -MT crypto/aes/aes-x86_64.o -c -o crypto/aes/aes-x86_64.o crypto/aes/aes-x86_64.s
gcc-5: error: x86_64: No such file or directory
gcc-5: error: unrecognized command line option '-arch'
make[1]: *** [crypto/aes/aes-x86_64.o] Error 1
make[1]: Leaving directory `/home/username/tmp/openssl@1.1-20161123-14873-1yzi8ju/openssl-1.1.0b'
make: *** [all] Error 2
```

**Comment by rwhogg** [comment] 2016-11-23 17:23
Hi @subunits! I think this is a duplicate of https://github.com/Linuxbrew/homebrew-core/issues/1187

Nevertheless, thanks for submitting the bug report to Linuxbrew 😸

**Closed by rwhogg** 2016-11-23 17:23 UTC

**Comment by subunits** [comment] 2016-11-23 17:25
Thank you for your time!
