### ISSUE TITLE
Random-number generation glibc compile error for pkg-config in old CentOS

### ISSUE THREAD

**Issue by nir-krakauer** [Linuxbrew/homebrew-core#1763] opened 2017-02-10 14:45 UTC
`brew install pkg-config` gives

```grand.c: In function 'g_rand_int_range':
grand.c:495:6: internal compiler error: Illegal instruction
      (G_RAND_DOUBLE_TRANSFORM +
```

[gist](https://gist.github.com/8f86a324e4f35d124d3da1c9c7d01417)

**Comment by sjackman** [comment] 2017-02-10 19:09
`CPU: dual-core 64-bit penryn`
https://gist.github.com/anonymous/8f86a324e4f35d124d3da1c9c7d01417#file-00-config-out-L12

Please discuss over at #1683.

**Comment by sjackman** [comment] 2017-02-10 19:09
Duplicate of https://github.com/Linuxbrew/homebrew-core/issues/1683

**Closed by sjackman** 2017-02-10 19:09 UTC
Labels: duplicate
