### ISSUE TITLE
binutils: Error: SHA256 mismatch

### ISSUE THREAD

**Issue by pusnaik2016** [Linuxbrew/homebrew-core#960] opened 2016-10-01 02:31 UTC
while installing "brew install hello", I have seen below error.
kick-bgl-cel:/ws/pusnaik-bgl/SSP_PYTHON > brew install hello
==> Installing dependencies for hello: patchelf, zlib, binutils, linux-headers, glibc, xz, gmp, gpatch, mpfr, libmpc, isl, gcc
==> Installing hello dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
###### ################################################################## 100.0%

==> Pouring patchelf-0.9_1.x86_64_linux.bottle.tar.gz
🍺  /users/pusnaik/.linuxbrew/Cellar/patchelf/0.9_1: 6 files, 1.2M
==> Installing hello dependency: zlib
==> Downloading https://linuxbrew.bintray.com/bottles/zlib-1.2.8.x86_64_linux.bottle.1.tar.gz
###### ################################################################## 100.0%

==> Pouring zlib-1.2.8.x86_64_linux.bottle.1.tar.gz
🍺  /users/pusnaik/.linuxbrew/Cellar/zlib/1.2.8: 11 files, 398.6K
==> Installing hello dependency: binutils
==> Downloading https://linuxbrew.bintray.com/bottles/binutils-2.27.x86_64_linux.bottle.tar.gz
###### ################################################################## 100.0%

Error: SHA256 mismatch
Expected: 7f47d549f79c74f6fef6442f6562f05b477a0d4304cbe0d76306f07b46969a16
Actual: f25883bb1ccd7d39d1d884e13a8ba0c904a0e1672e5642726c6043fabd45fc99
Archive: /users/pusnaik/.cache/Homebrew/binutils-2.27.x86_64_linux.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Downloading https://ftpmirror.gnu.org/binutils/binutils-2.27.tar.gz
==> Downloading from http://infinity.kmeacollege.ac.in/gnu/binutils/binutils-2.27.tar.gz
###### ################################################################## 100.0%

Error: SHA256 mismatch
Expected: 26253bf0f360ceeba1d9ab6965c57c6a48a01a8343382130d1ed47c468a3094f
Actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Archive: /users/pusnaik/.cache/Homebrew/binutils-2.27.tar.gz
To retry an incomplete download, remove the file above.
# System details

kick-bgl-cel:/ws/pusnaik-bgl/SSP_PYTHON > uname -a
Linux kick-bgl-cel 2.6.32-504.12.2.el6.x86_64 #1 SMP Sun Feb 1 12:14:02 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rwhogg** [comment] 2016-10-01 02:39
Can you try doing `rm /users/pusnaik/.cache/Homebrew/binutils-2.27.x86_64_linux.bottle.tar.gz` and then retrying the installation? (My apologies if you've already tried that).

Thanks a bunch!

**Comment by pusnaik2016** [comment] 2016-10-01 05:10
I tried, but it the same issue.

BR,
Pushparaj

2016-10-01 8:09 GMT+05:30 Bob W. Hogg <notifications@github.com>:

**Comment by rwhogg** [comment] 2016-10-01 19:16
You could try downloading the files manually with `wget` and copying them into your Homebrew cache folder. If that fails, I would use tar/gunzip to look at the downloaded bottle and see what's inside it. I'd understand if a given source mirror occasionally had corrupted downloads, but I find it strange that you're getting a different bottle even though you're using the same download location as everyone else.

**Comment by pusnaik2016** [comment] 2016-10-03 05:01
I downloaded the file manually to homebrew cache
folder /users/pusnaik/.linuxbrew.  Here I found there is no file to install
"./configure" and "make" after unzipping.

Seems something broken ?

BR,
Pushparaj

2016-10-02 0:46 GMT+05:30 Bob W. Hogg <notifications@github.com>:

**Comment by rwhogg** [comment] 2016-10-07 02:05
Not having a `configure` script after downloading is pretty weird. It's common when checking out code directly from Git, but GNU release tarballs usually have them. They can usually be regenerated with `autoreconf`, but for now I'd suggest downloading from a different mirror. Either use `wget` to download from a different GNU mirror or change the URL in the `binutils` formula.

I can't reproduce this problem with the bottle, so marking as unreproducible.

**Comment by sjackman** [comment] 2016-10-07 08:02
Hi, @pusnaik2016. I see that Bob has already suggested this, but please once again try:
```sh
rm -f /users/pusnaik/.cache/Homebrew/binutils-2.27.x86_64_linux.bottle.tar.gz
brew fetch binutils
```
and report the exact output that you see copied and pasted from your screen verbatim.
This issue is very strange indeed.

**Closed** 2017-05-14 22:25 UTC
Labels: build-error, needs response, unreproducible
