### ISSUE TITLE
Error while upgrading rust

### ISSUE THREAD

**Issue by thedrow** [Linuxbrew/homebrew-core#10792] opened 2018-12-23 09:09 UTC
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/d73e7ff74fca89dd6e495630c55fcced
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade rust
- What happened (include command output)
```
==> Upgrading rust 
==> Downloading https://linuxbrew.bintray.com/bottles/rust-1.31.1.x86_64_linux.b
==> Downloading from https://akamai.bintray.com/37/3718710510639dce34232b0dba53b
######################################################################## 100.0%
==> Pouring rust-1.31.1.x86_64_linux.bottle.tar.gz
Error: wrong number of arguments (given 1, expected 2)
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:548:in `block in initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:557:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:557:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:10:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:10:in `safe_popen_read'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:134:in `needed_libraries_using_readelf'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:111:in `needed_libraries'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:87:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:150:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:150:in `metadata'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:158:in `dynamically_linked_libraries'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:98:in `block in check_dylibs'
/usr/lib/ruby/2.5.0/pathname.rb:565:in `block in find'
/usr/lib/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
/usr/lib/ruby/2.5.0/find.rb:48:in `catch'
/usr/lib/ruby/2.5.0/find.rb:48:in `block in find'
/usr/lib/ruby/2.5.0/find.rb:43:in `each'
/usr/lib/ruby/2.5.0/find.rb:43:in `find'
/usr/lib/ruby/2.5.0/pathname.rb:565:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:91:in `check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/linkage_checker.rb:23:in `check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:25:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:646:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:646:in `block in finish'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cache_store.rb:15:in `use'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:643:in `finish'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:164:in `upgrade_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:109:in `block in upgrade_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:84:in `upgrade'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```
- What you expected to happen
Rust should be upgraded
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew upgrade rust`

**Comment by iMichka** [comment] 2018-12-27 15:39
Hi. Could you please try to print out the content of the `command` variable in: 
`/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:134:in `needed_libraries_using_readelf'`?

I would like to see what is executed. 

Also, what is happening in:
`/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:10:in `safe_popen_read'` ?
Is `$CHILD_STATUS` set to `nil`?

I can not reproduce this error, so we need more output to see what is going on.

**Comment by thedrow** [comment] 2019-01-06 10:59
Will there be a migration guide or a notice on when should we move?

**Comment by iMichka** [comment] 2019-01-09 22:06
Brew 1.9.0 has been released. We will still merge the changes to linuxbrew and tag a new release there too.

The migration will be automatic for everyone, so you will not need to do anything on your side. It looks like the migration script will come with brew 2.0 and will run on brew upgrade, setting up everything for you.

**Comment by iMichka** [comment] 2019-01-10 11:03
Closing here as I believe that this problem has been solved.

**Closed by iMichka** 2019-01-10 11:03 UTC
Labels: bug
