### ISSUE TITLE
portmidi does not build

### ISSUE THREAD

**Issue by sstark** [Linuxbrew/homebrew-core#796] opened 2016-08-20 22:27 UTC
Build fails at configure step:

```
-- Configuring incomplete, errors occurred!
See also "/tmp/portmidi-20160821-20065-17allxk/portmidi/Release/CMakeFiles/CMakeOutput.log".
pm_mac/Makefile.osx:26: recipe for target 'Release/CMakeCache.txt' failed
make: *** [Release/CMakeCache.txt] Error 1
```

Reason seems to be that it is trying to use the osx makefile.

https://gist.github.com/anonymous/e4c4bcc53df2ad9a92d05458fe025b84

**Comment by rwhogg** [comment] 2016-09-02 15:03
Attempting to reproduce at https://github.com/Linuxbrew/homebrew-core/pull/857. Thanks a bunch for the bug report and sorry it took so long to respond!

Unfortunately, I think it's going to take more than just fixing the Makefile issue to get `portmidi` to build. Last I checked, it had a dependency on `alsa` on Linux, which isn't packaged for Linuxbrew.

**Comment by sstark** [comment] 2016-09-02 16:37
Here's a formula for libasound, would that help? Sorry, I could not figure out how to properly submit this as a pull request.

```
class AlsaLib < Formula
  desc "provides audio and MIDI functionality to the Linux operating system."
  homepage "http://www.alsa-project.org/"
  url "ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.2.tar.bz2"
  version "1.1.2"
  sha256 "d38dacd9892b06b8bff04923c380b38fb2e379ee5538935ff37e45b395d861d6"

  def install
    system "./configure", "--disable-debug",
                          "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--prefix=#{prefix}"
    system "make", "install"
  end

  test do
    (testpath/"test.c").write <<-EOS.undent
    #include <alsa/asoundlib.h>
    int main(void)
    {
        snd_ctl_card_info_t *info;
        snd_ctl_card_info_alloca(&info);
     }
    EOS
    system ENV.cc, "test.c", "-L#{lib}", "-lasound", "-o", "test"
    system "./test"
  end
end
```

**Comment by rwhogg** [comment] 2016-09-02 20:32
@sstark that's awesome, thanks! :smiley_cat: 

What part of submitting it as a PR were you having trouble with? (I could open the PR for it myself, and I will if you'd prefer, but I'd be happier to see you get proper credit)

**Comment by sstark** [comment] 2016-09-02 20:38
I'm not very experienced with github :) The formula cookbook I looked at for creating this seems to be for the osx version only. Which repository should I fork and submit back to for a linux-only formula?

**Comment by rwhogg** [comment] 2016-09-02 20:44
> Which repository should I fork and submit back to for a linux-only formula?

It doesn't actually matter which one you fork from - you can submit PR's back to either Homebrew or Linuxbrew from the same fork - but I'd recommend forking whichever one you use more often.

Regardless of the one you fork from, please submit this PR to Linuxbrew. On the Github page of your fork, when you do the branch comparison, you can change the repo you wish to make the PR against.

**Comment by sstark** [comment] 2016-09-02 21:16
will try, thanks for your help!

**Comment by jabbink** [comment] 2016-11-30 10:26
Just ran into this problem myself.

I changed the `homebrew-core/Formula/portmidi.rb` to use the normal make file (generated by cmake).

It also didn't work. Downloaded the source from sourceforge and followed their build instructions. Also fails, as it tries to link against `/Release/libpmjni.so`. Searched through the CMakeLists files, but couldn't see why I it would look there. Also, unfortunately, I don't have the time for this now as I don't necessarily need `portmidi`, but as far as I am concerned this looks like this is a problem with portmidi.

**Comment by sjackman** [comment] 2016-11-30 16:05
Thanks for the feedback, Jasper.

**Comment by rwhogg** [comment] 2016-12-25 16:48
I've made further progress on this issue at #857, which requires both using CMake and patching one of the CMakeLists.txt files.

If anyone would like to continue working on that PR, it would be greatly appreciated. I apologize, but I lack the time to dig further into it myself.

**Comment by iMichka** [comment] 2017-12-29 21:25
I'll close this issue as nobody has been working on this since a year now. Pull requests are welcome to fix this.

**Closed by iMichka** 2017-12-29 21:25 UTC
Labels: build-error, help wanted
