### ISSUE TITLE
binutils: ld 2.28 seems unable to parse glibc.so script file

### ISSUE THREAD

**Issue by bluddy** [Linuxbrew/homebrew-core#3073] opened 2017-06-27 20:34 UTC
I just installed linuxbrew on what I think is a Red Hat system (not sure, I'm just one of many users). Installing gcc and therefore glibc is my first action. What I noticed after trying to install some other packages (pkg-config, openssl) is that a libc.so file is installed in my lib directory that ld considers invalid. I can't even compile a regular C file with gcc: gcc test.c -o test of a hello world file gives me the error

`/home-4/XXX/.linuxbrew/lib/libc.so: file not recognized: File format not recognized`

Getting more verbose output from ld using gcc test.c -o test -Wl,--verbose gives me

    attempt to open /home-4/XXX/.linuxbrew/lib/libc.so succeeded
    opened script file /home-4/XXX/.linuxbrew/lib/libc.so
    /home-4/XXX/.linuxbrew/lib/libc.so: file not recognized: File format not recognized
    collect2: error: ld returned 1 exit status

Not sure if this is ld 2.28 or something else. The actual libc.so file contains

    /* GNU ld script
       Use the shared library, but some functions are only in
       the static library, so try that secondarily.  */
    OUTPUT_FORMAT(elf64-x86-64)
    GROUP ( /home-4/XXX/.linuxbrew/Cellar/glibc/2.19/lib/libc.so.6 /home-
    4/XXX/.linuxbrew/Cellar/glibc/2.19/lib/libc_nonshared.a  AS_NEEDED ( /home-
    4/XXX/.linuxbrew/Cellar/glibc/2.19/lib/ld-linux-x86-64.so.2 ) )

Which seems fine. I've also made sure the right gcc/ld is running.

Any ideas?

**Comment by sjackman** [comment] 2017-06-27 20:39
Can you determine whether the brewed `ld` or the host's `ld` is being run?

**Comment by bluddy** [comment] 2017-06-27 20:42
Host's `/usr/bin/ld` is version 2.20, and `ld`'s verbose output clearly shows 2.28. gcc version is also 5.3.0, far ahead of `usr/bin/gcc`'s 4.4.7, for what it's worth.

**Comment by sjackman** [comment] 2017-06-27 21:41
Oh, wait. I have an idea. Can you open the file `/home-4/XXX/.linuxbrew/lib/libc.so` in a text editor and look for at characters `@@`?

**Comment by sjackman** [comment] 2017-06-27 21:43
Never mind. You posted the file contents, and it looks fine.

**Comment by sjackman** [comment] 2017-06-27 21:43
If `brew install hello` fails, can you please post the output of `brew gist-logs hello` ?

**Comment by bluddy** [comment] 2017-06-27 21:54
`brew install hello` fails as well (which is predictable, since I can't link anything)

[gist](https://gist.github.com/b164ccf8ebfce3cdb507201b1ec253da)

**Comment by sjackman** [comment] 2017-06-27 21:59
You have an `@` sign in your home directory, and that breaks `binutis`.

**Comment by sjackman** [comment] 2017-06-27 22:02
This issue has come up once before: https://github.com/Linuxbrew/homebrew-core/issues/814
If you're interested, would you consider submitting a PR to `Linubrew/brew` to add a check to `brew doctor` to report an error if the Linuxbrew installation directory contains an `@` character.

**Comment by sjackman** [comment] 2017-06-27 22:03
Duplicate of https://github.com/Linuxbrew/homebrew-core/issues/814

**Closed by sjackman** 2017-06-27 22:03 UTC

**Comment by bluddy** [comment] 2017-06-28 01:08
Thanks so much! Sorry for taking up your time.

**Comment by sjackman** [comment] 2017-06-28 02:12
No worries, Yotam. It's a pretty obscure issue.

**Comment by sjackman** [comment] 2017-06-28 02:13
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula.
