### ISSUE TITLE
Unable to install glibc -- Error: No such file or directory @ realpath_rec - (...)/bin/gcc-4.8

### ISSUE THREAD

**Issue by muffato** [Linuxbrew/homebrew-core#5626] opened 2018-01-16 15:10 UTC
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [N/A] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [N/A] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

-----

I am trying to set up a new, local, linuxbrew environment with graphviz, but the installation fails at the gllibc.

```
==> Installing glibc
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
######################################################################## 100.0%
Error: No such file or directory @ realpath_rec - /home/guest/my_graphviz/bin/gcc-4.8
```

My host OS is Ubuntu 14.04. It's got gcc and g++ installed. The issue seems related to #5339 and I have been able to find a fix there. However I don't understand why linuxbrew is not able to use the host OS' gcc.

You can find the logs at https://gist.github.com/9986565752b49fc0ecc57d56332b6c89

I have managed to reproduce the whole issue with docker: `docker run -it ubuntu:14.04`

```
# apt-get update
# apt-get install build-essential git curl gawk
# useradd -m guest
# su guest
$ cd
$ export LOCAL_BREW_ENV="$HOME/my_graphviz"
$ mkdir -p "$LOCAL_BREW_ENV"
$ git clone https://github.com/Linuxbrew/brew.git "$LOCAL_BREW_ENV"
$ export PATH="$LOCAL_BREW_ENV/bin:$LOCAL_BREW_ENV/sbin:$PATH"
$ export MANPATH="$LOCAL_BREW_ENV/share/man:$MANPATH"
$ export INFOPATH="$LOCAL_BREW_ENV/share/info:$INFOPATH"
$ export HOMEBREW_CACHE="$LOCAL_BREW_ENV/var/cache"
$ export HOMEBREW_LOGS="$LOCAL_BREW_ENV/var/log"
$ brew vendor-install ruby
$ brew doctor
$ brew install glibc
```

`brew doctor` is mostly happy. There is just a warning about locales, that I haven't configured under Docker, but I don't have this warning on my host OS.

Then, installing glibc fails:
```
==> Installing glibc
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
######################################################################## 100.0%
Error: No such file or directory @ realpath_rec - /home/guest/my_graphviz/bin/gcc-4.8
```

Additional reports suggested by #5339 
```
guest@2827a0cad089:~$ which -a gcc g++
/usr/bin/gcc
/usr/bin/g++
guest@2827a0cad089:~$ ls -l /usr/bin/gcc /usr/bin/g++ $(brew --prefix)/bin/gcc $(brew --prefix)/bin/g++
/home/guest/my_graphviz/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
/home/guest/my_graphviz/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
ls: cannot access /home/guest/my_graphviz/bin/gcc: No such file or directory
ls: cannot access /home/guest/my_graphviz/bin/g++: No such file or directory
lrwxrwxrwx 1 root root 7 Apr  7  2014 /usr/bin/g++ -> g++-4.8
lrwxrwxrwx 1 root root 7 Apr  7  2014 /usr/bin/gcc -> gcc-4.8
guest@2827a0cad089:~$ /usr/bin/gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

guest@2827a0cad089:~$ /usr/bin/g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Adding symlinks like in #5339 solved the issue:
```
# ln -s /usr/bin/gcc-4.8 /usr/bin/g++-4.8 ~guest/my_graphviz/bin/
```
```
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
Already downloaded: /home/guest/my_graphviz/var/cache/glibc-2.23.tar.gz
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/home/guest/my_graphviz/Cellar/glibc/2.23 --enable-obsolete-rpc --without-selinux --with-binutils=/home/guest/my_graphviz
==> make
==> make install
==> Installing locale data for en_US.UTF-8
==> /home/guest/my_graphviz/Cellar/glibc/2.23/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
🍺  /home/guest/my_graphviz/Cellar/glibc/2.23: 1,367 files, 81.7MB, built in 6 minutes 25 seconds
```

**Comment by iMichka** [comment] 2018-01-16 22:56
Hi. Thanks for reporting.
See that comment: https://github.com/Linuxbrew/homebrew-core/issues/5339#issuecomment-355624350

> It is supposed to automatically use /usr/bin/gcc when it's available. It creates automatically a symlink from /usr/bin/gcc to $HOMEBREW_PREFIX/bin/gcc-4.9. As far as I know, that works.

We had no time to investigate this. It would be great if you could have look at this. The solution you used is the right one, but it should have been automatic.

Adding @sjackman because @muffato nicely added a docker file which reproduces the error; which will probably help solve the issue.

**Comment by sjackman** [comment] 2018-01-17 00:09
Thanks for the very helpful bug report, Matthieu. This bug should be resolved by PR https://github.com/Linuxbrew/homebrew-core/pull/5631

**Closed by sjackman** 2018-01-17 00:09 UTC
Labels: bug

**Comment by muffato** [comment] 2018-01-17 01:18
Yes it works ! Thanks a lot for the quick fix; your solution looks a bit like dark magic to me, TBH ^^

**Comment by sjackman** [comment] 2018-01-17 01:26
I was expecting to find `gcc-4.8` in `$HOMEBREW_PREFIX/bin`, and I wasn't handling the case when it's found instead in `/usr/bin`. 🙈
